client.println("
<!DOCTYPE html>");
client.println("<html lang=\"en\">");
client.println("");
client.println("

<head>");
    client.println("
    <meta charset=\"UTF-8\">");
    client.println("
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
    client.println("
    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
    client.println("
    <meta http-equiv=\"refresh\" content=\"5\">");
    client.println("
    <link href=\"https://fonts.googleapis.com/css?family=Eagle+Lake|Montserrat\" rel=\"stylesheet\">");
    client.println("<style>
        ");
client.println("    * {");
        client.println("        text-align: center;");
        client.println("        margin: 0;");
        client.println("    }");
        client.println("");
        client.println("    body {");
        client.println("        background-color: #82b6e6;");
        client.println("        font-family: 'Montserrat', sans-serif;");
        client.println("    }");
        client.println("");
        client.println("    .section {");
        client.println("        border-radius: 15px 50px 30px;");
        client.println("        width: 80vw;");
        client.println("        height: 90vh;");
        client.println("        margin-left: 10vw;");
        client.println("        margin-bottom: 50px;");
        client.println("    }");
        client.println("");
        client.println("    .section h2 {");
        client.println("        padding-top: 40vh;");
        client.println("        font-size: 50px;");
        client.println("        font-weight: 200px;");
        client.println("    }");
        client.println("");
        client.println("    .menu {");
        client.println("        position: fixed;");
        client.println("        width: 80vw;");
        client.println("        margin-left: 10vw;");
        client.println("        opacity: 0.8;");
        client.println("    }");
        client.println("");
        client.println("    .menu a {");
        client.println("        padding: 10px 15px;");
        client.println("        float: right;");
        client.println("        text-decoration: none;");
        client.println("        font-size: 18px;");
        client.println("        background-color: white;");
        client.println("    }");
        client.println("");
        client.println("    .menu a:hover {");
        client.println("        background-color: whitesmoke;");
        client.println("    }");
        client.println("");
        client.println("    #all {");
        client.println("        height: 40%;");
        client.println("        padding-bottom: 10%;");
        client.println("    }");
        client.println("");
        client.println("    #all h1 {");
        client.println("        padding-top: 10%;");
        client.println("        padding-bottom: 2%;");
        client.println("        font-size: 50px;");
        client.println("    }");
        client.println("");
        client.println("    #wind {");
        client.println("        background-image: url(\"https://firebasestorage.googleapis.com/v0/b/fir-images-851b6.appspot.com/o/windy-png-hd-breeze-breezy-gust-of-wind-light-breeze-summer-weather-windy-512.png?alt=media&token=f2c1da8e-49b1-4564-8c0e-2e53a14b5e5f\");");
        client.println("        background-size: 400px;");
        client.println("        background-color: #a4dda4;");
        client.println("    }");
        client.println("");
        client.println("    #temp {");
        client.println("        background: url(\"https://firebasestorage.googleapis.com/v0/b/fir-images-851b6.appspot.com/o/thermometer-pngrepo-com.png?alt=media&token=de18912c-6c3f-442c-97e4-cd52cc8b2be2\");");
        client.println("        background-size: 200px;");
        client.println("        background-repeat: space 200px 200px;");
        client.println("        background-color: #3b484d;");
        client.println("        color: #f8f2ff;");
        client.println("    }");
        client.println("");
        client.println("    #light {");
        client.println("        background: url(\"https://firebasestorage.googleapis.com/v0/b/fir-images-851b6.appspot.com/o/pixar-lamp-2.png?alt=media&token=3ca2d01a-4a35-4057-b221-76bf70443816\") space 50px 50px;");
        client.println("        background-size: 250px;");
        client.println("        background-color: #bbd3f0;");
        client.println("        color: white;");
        client.println("    }");
        client.println("");
        client.println("    @media only screen and (max-width: 1600px) {");
        client.println("        #all {");
        client.println("            height: 50vh;");
        client.println("        }");
        client.println("");
        client.println("        #all h1 {");
        client.println("            padding-bottom: 5vh;");
        client.println("            font-size: 50px;");
        client.println("        }");
        client.println("");
        client.println("        .section {");
        client.println("            width: 90%;");
        client.println("            margin: 0% 5% 5% 5%;");
        client.println("        }");
        client.println("");
        client.println("        .menu {");
        client.println("            right: 0;");
        client.println("            width: 100vw;");
        client.println("        }");
        client.println("");
        client.println("        .menu a {");
        client.println("            width: 25vw;");
        client.println("            padding: 10px 0;");
        client.println("            font-size: 15px;");
        client.println("        }");
        client.println("    }");
        client.println("");
        client.println("    @media only screen and (max-width: 600px) {");
        client.println("        .section {");
        client.println("            border-radius: 0;");
        client.println("            width: 100%;");
        client.println("            margin: 0;");
        client.println("            height: 60vh;");
        client.println("        }");
        client.println("");
        client.println("        .section h2 {");
        client.println("            padding-top: 30vh;");
        client.println("            font-size: 40px;");
        client.println("            font-weight: 200px;");
        client.println("        }");
        client.println("");
        client.println("        #all {");
        client.println("            height: 40vh;");
        client.println("            padding-bottom: 10%;");
        client.println("        }");
        client.println("");
        client.println("        #all h1 {");
        client.println("            padding-top: 20%;");
        client.println("            padding-bottom: 10%;");
        client.println("            font-size: 50px;");
        client.println("        }");
        client.println("    }");
        client.println("
    </style>");
    client.println(" <title>Mount Lake Resort</title>");
    client.println("</head>");
client.println("");
client.println("

<body>");
    client.println(" <div class=\"menuCont\">");
        client.println(" <div class=\"menu\">");
            client.println(" <a href=\"#light\">Light</a>");
            client.println(" <a href=\"#wind\">Wind</a>");
            client.println(" <a href=\"#temp\">Temperature</a>");
            client.println(" <a href=#all>Home</a>");
            client.println(" </div>");
        client.println(" </div>");
    client.println(" <header id=\"all\" class=\"section\">");
        client.println(" <h1>Mount Lake Resort</h1>");
        client.println(" Wind-speed:" + windSwitch(currWind));
        client.println(" <br>");
        client.println(" Temperature: " + String((int)round(tempC)) + " C " + " &#176;" + String((int)round(tempF)) + "
        F" + " &#176;");
        client.println(" <br>");
        client.println(" light:" + String(lightSwitch(lux)));
        client.println(" </header>");
    client.println("");
    client.println("");
    client.println(" <div class=\"section\" id=\"temp\">");
        client.println(" <h2> Temperature</br>" + String((int)round(tempC)) + " C" + " &#176; " +
            String((int)round(tempF)) + "F &#176; </h2> ");
        client.println(" </div> ");
    client.println(" <div class=\"section\" id=\"wind\">");
        client.println(" <h2>Wind Speeds</br>" + windSwitch(currWind) + "</h2>");
        client.println(" </div>");
    client.println(" <div class=\"section\" id=\"light\">");
        client.println(" <h2>Ambient Light</br>" + lightSwitch(avgLight) + "</h2>");
        client.println(" </div>");
    client.println(" <footer></footer>");
    client.println("</body>");
client.println("");
client.println("

</html>");